---

- hosts: all
  gather_facts: no
  tasks:

    - name: install python | debian >>>
      raw: "apt-get -y install python-minimal python-dev"
      register: install
      changed_when:
        - not install.stdout|search("0 upgraded, 0 newly installed")
        - not install.stdout|search("command not found")
      failed_when: false

    - name: install python | redhat >>>
      raw: "yum -y install python"
      register: install
      changed_when:
        - not install.stdout|search("Nothing to do")
        - not install.stdout|search("command not found")
      failed_when: false

- hosts: all
  vars:
  tasks:

    - name: dist-upgrade | debian >>>
      apt:
        autoremove: yes
        cache_valid_time: 3600
        purge: yes
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: dist-upgrade | redhat >>>
      yum:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: install packages | debian >>>
      apt:
        name: "{{item}}"
      with_items:
        - bash-completion
        - htop
        - locales-all
        - screen
        - vim
      when: ansible_os_family == "Debian"

    - name: install epel-release | redhat >>>
      yum:
        name: epel-release
      when: ansible_os_family == "RedHat"

    - name: install packages | redhat >>>
      yum:
        name: "{{item}}"
      with_items:
        - bash-completion
        - htop
        - screen
        - vim
      when: ansible_os_family == "RedHat"

